export const clientRoutes = {
  main: "/",
  auth: "/auth",
  back: "/back",
  frontendFactors: "/frontendFactors",
  testerFactors: "/testerFactors",
  analistFactors: "/analistFactors",
  sqlFactors: "/sqlFactors",
  analistForm1: "/analistForm1",
  analistForm2: "/analistForm2",
  analistForm3: "/analistForm3",
  analistForm4: "/analistForm4",
  analistForm5: "/analistForm5",
  analistForm6: "/analistForm6",
  analistForm7: "/analistForm7",
  analistForm8: "/analistForm8",
  analistForm9: "/analistForm9",
  analistForm10: "/analistForm10",
  backendFactors: "/backendFactors",
  backForm1: "/backForm1",
  backForm2: "/backForm2"
};
