export type TGetBackTaskFactors = {
    user_id: string;
    access: number;
    job : number;
    model: number;
    instrument: number;
    infra : number;
    specs : number;
    tables : number;
    test_data : number;
    entity : number;
    buz_func : number;
    end_point : number;
    io_data : number;
    web_client : number;
    brocker : number;
    r_and_d : number;
    unit_test : number;
    log : number;
    migration : number;
    comments : number;
    auto_label: number;
    create_date: string;
    status: string;
    user_label_sp: number;
    user_label_hr: number;
    nazvanie: string;
    user_comments: string;
    description: string;
};

export type TGetBackTaskFactorsResponce = string;